name: moneytoring
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  introduction_screen: ^3.1.17
  sizer: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/moneytoring_icon_nobg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/icon/
