// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwR3p6QwzlyVelTWlxN8f6WW-clhYX8Ow',
    appId: '1:530516252416:web:ab562a6466bc12196d45e5',
    messagingSenderId: '530516252416',
    projectId: 'moneytoring-6be03',
    authDomain: 'moneytoring-6be03.firebaseapp.com',
    storageBucket: 'moneytoring-6be03.firebasestorage.app',
    measurementId: 'G-PGRX8NGWL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGyNusqvOyAKJfQo8x2otQqR_oNePeSFc',
    appId: '1:530516252416:android:9c7fdbd873dd34256d45e5',
    messagingSenderId: '530516252416',
    projectId: 'moneytoring-6be03',
    storageBucket: 'moneytoring-6be03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR_mTej10jifIsxh3KwfsycaBeAGNmIFg',
    appId: '1:530516252416:ios:9283588196585a8f6d45e5',
    messagingSenderId: '530516252416',
    projectId: 'moneytoring-6be03',
    storageBucket: 'moneytoring-6be03.firebasestorage.app',
    iosBundleId: 'com.example.moneytoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR_mTej10jifIsxh3KwfsycaBeAGNmIFg',
    appId: '1:530516252416:ios:9283588196585a8f6d45e5',
    messagingSenderId: '530516252416',
    projectId: 'moneytoring-6be03',
    storageBucket: 'moneytoring-6be03.firebasestorage.app',
    iosBundleId: 'com.example.moneytoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwR3p6QwzlyVelTWlxN8f6WW-clhYX8Ow',
    appId: '1:530516252416:web:873e57de1266724b6d45e5',
    messagingSenderId: '530516252416',
    projectId: 'moneytoring-6be03',
    authDomain: 'moneytoring-6be03.firebaseapp.com',
    storageBucket: 'moneytoring-6be03.firebasestorage.app',
    measurementId: 'G-LP0XWE5TM2',
  );
}
